### ISSUE TITLE
support RPM/temperature sensor

### ISSUE THREAD

**Issue by marcmerlin** [athertop/MavLink_FrSkySPort#13]
As explained in https://github.com/ArduPilot/ardupilot/issues/6296 , ardupilot sorely lacks support for a generic RPM sensor and temperature sensors.
Support for this, would be fantastic
http://alofthobbies.com/frsky-sp-rpm-smart-port-rpm-and-dual-temperature-sensor.html
![image](https://cloud.githubusercontent.com/assets/1369412/26294033/cb0ad544-3e75-11e7-8770-5b9cb7b48012.png)
However if I understand properly, this wouldn't actually help me in the situation here I'd have the teensy located on the TX side, but it may be helpful to others who are plugging the teensy in the X8R.

https://github.com/athertop/MavLink_FrSkySPort/wiki/1.-Setup hints that the teensy needs to know which additional sport sensors are connected (so as not to conflict with them?)
If no software change is required, feel free to close this request/suggestion with prejudice :)

**Comment by athertop** [comment]
Marc, its a nice idea, but I feel a bit too messy to implement as the FrSky Tmp sensor is utilised already for another purpose on this project - we had to find homes for Mavlink sensors where compatible SmartPort sensors didn't exist, so re-purposed some of the Smartport sensors to do this, including the Tmp sensor. I have made the move myself to using the Passthrough telemetry now, using yaapu's excellent telemetry script found here: https://github.com/yaapu/FrskyTelemetryScript. If4 you're using FrSky X series Rx then no need for a Teensy (just needs an inverter between Pixhawk serial port and the smartport connection). For LRS setups such as ULRS/Dragonlink with serial Mavlink output at the ground side, I use the teensy setup in this project: https://github.com/zs6buj/MavlinkToPassthru
Both these projects are a generation ahead of what you find in my repo here, and I highly recommend both.
