### ISSUE TITLE
TxBat showing 0.0v on Telemetry Screen

### ISSUE THREAD

**Issue by maroquio** [athertop/MavLink_FrSkySPort#16]
Hi. In the top middle of main telemetry screen, there is a field called TxBat that is supposed to show the Taranis battery level. The problem is that it's showing only 0.0v, all the time. The original initial screen of Taranis shows the Tx voltage, but the athertop telemetry main screen have this problem. Is this a bug or am I missing something? PS: My Taranis is flashed with the latest firmware.

**Comment by athertop** [comment]
Hi, I have the latest release of OpenTx (2.2.0) on my Taranis X9D plus, but can not reproduce this issue - the TxBat: value reads correctly on mine. The LUA script simply references the inbuilt telemetry value "tx-voltage". Are you running OpenTx v2.2.0 ? This telemetry value is reported working in both OpenTx v 2.1.9 and v2.2 by the OpenTx devs when I checked.

**Comment by athertop** [comment]
No response - closing
