### ISSUE TITLE
rangefinder altitude

### ISSUE THREAD

**Issue by geofrancis** [athertop/MavLink_FrSkySPort#19]
i want to program the taranis with terrain warning alarms, so if the rangefinder detects anything under it closer than say 20m i can make the handset shout "TERRAIN TERRAIN PULL UP"! like a ground proximity alarm on real aircraft. im already using the airspeed for a stick shaker so if the airspeed gets too low it vibrates and shouts "STALL"

i tried using regular altitude but it doesnt change with terrain, it just flashes "ALT VARIANCE" on the screen

**Comment by athertop** [comment]
I think it would need two things to make this work. First is that you would need to get the teensy to convert/assign the rangefinder altitude to a s.port sensor - making this available as a sensor in the Taranis. The voice could be setup without LUA, but just with a logical switch and a special function to call the WAV file (and a wav file of course!)

**Comment by geofrancis** [comment]
i was thinking replace the Galt sensor with the rangefinder altitude since GPS altitude is not used for anything on the lua.

everything else i can do with logic switches if i can get the data.

**Comment by athertop** [comment]
That could definitely be done. Is there a telemetry value which starts as rangefinder value then drops to baro altitude once max range is exceeded? Could use this, would be best to replace AGL Alt value (just shown as Alt) on display with this if it exists in mavlink?

**Comment by geofrancis** [comment]
I don't think so,  as far as I know all the altitude sensors are treated separately

**Comment by athertop** [comment]
Found this in the message spec. Not sure which data stream that's in but when I have some time I can maybe have a look at the code. I could give an option to use it instead of Alt - I.e. send rangefinder on the Alt telemetry sensor instead of Baro Alt:
http://mavlink.org/messages/ardupilotmega#RANGEFINDER

**Comment by geofrancis** [comment]
alt is useful and needed for the lua whereas Galt is not used for anything so i would prefer to sacrifice Galt over baro altitude.

**Comment by athertop** [comment]
Looks like the rangefinder data is included in the EXTRA3 stream. See here: http://ardupilot.org/copter/docs/parameters.html#sr0-extra3-extra-data-type-3-stream-rate-to-ground-station

You're right George, the gAlt we could afford to lose.

**Comment by athertop** [comment]
George - Just done the mods to the code in the dev branch give it a go and let me know if it works. Cheers

**Comment by athertop** [comment]
Its just the Teensy code which has changed - you'll need to uncomment the line:

//#define  USE_RF_ALT in MavLink_FrSkySPort.ino

**Comment by geofrancis** [comment]
nice il try it as soon as i get a chance.

**Comment by athertop** [comment]
George, Did you get a chance to test this?? Not planning to continue maintenance on this project so hoping to close off all the issues. Cheers, Paul
