### ISSUE TITLE
RTK Status

### ISSUE THREAD

**Issue by geofrancis** [athertop/MavLink_FrSkySPort#20]
I was looking through the lua code and I see it only looks to see if the gps status is over 3 to signify 3d gps lock, 

https://github.com/athertop/MavLink_FrSkySPort/blob/Mav_Sport2.1-2.2-master/Taranis/LUA_Source_files/SCRIPTS/TELEMETRY/LIBRARY/mainrun.lib :257

could that be modified to show mode 4 (RTK float) and mode 5 (RTK fix) also?

**Comment by athertop** [comment]
I guess this can be done, but will need to wait until I have more time. Cheers, P

**Comment by geofrancis** [comment]
cool il try just changing 2d to 3d and 3d to rtk fix.

**Comment by geofrancis** [comment]
would changing this:

> if telem_lock >= 3 then
> 			lcd.drawText (168, 10, "3D",0)
> 			lcd.drawNumber (195, 10, telem_sats, 0+LEFT)
> 			lcd.drawText (lcd.getLastPos(), 10, "S", 0)
> 		elseif telem_lock>1 then
> 			lcd.drawText (168, 10, "2D", 0)
> 			lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
> 			lcd.drawText (lcd.getLastPos(), 10, "S", 0)
> 		else
> 			lcd.drawText (168, 10, "NO", 0+BLINK+INVERS)
> 			lcd.drawText (195, 10, "--S",0)
> end

to this work?

> if telem_lock >= 5 then
> 			lcd.drawText (168, 10, "FX",0)
> 			lcd.drawNumber (195, 10, telem_sats, 0+LEFT)
> 			lcd.drawText (lcd.getLastPos(), 10, "S", 0)
> 		elseif telem_lock=4 then
> 			lcd.drawText (168, 10, "FL", 0)
> 			lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
> 			lcd.drawText (lcd.getLastPos(), 10, "S", 0)
>                     elseif telem_lock=3 then
> 			lcd.drawText (168, 10, "3D", 0)
> 			lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
> 			lcd.drawText (lcd.getLastPos(), 10, "S", 0)
> 
>                 elseif telem_lock=2 then
> 			lcd.drawText (168, 10, "2D", 0)
> 			lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
> 			lcd.drawText (lcd.getLastPos(), 10, "S", 0)
> 		else
> 			lcd.drawText (168, 10, "NO", 0+BLINK+INVERS)
> 			lcd.drawText (195, 10, "--S",0)
> end

**Comment by athertop** [comment]
George, Your suggested code looks spot on! Give it a go and let me know if it works - Actually, would be better if I could compile that luac version for you to test it (I don't have RTK setup to be able to do this). I'll see if I can do that tonight and update the dev repo. 

Couple other things - I don't think the GPS updates unless its got at least a 3D fix (- spotted some statements in the Teensy code to that end), so don't know why the LUA caters for a 2D fix if it will never be displayed. Could possibly fix the Teensy code to rectify this. EDIT: I misread the teensy code - it still sends the fixtype even with less than 3 - its lat/long, gAlt and COG that's not sent unless >=3 (kinda makes sense!)

Second thing - a value of 4 suggests DGPS fix, so not necessarily related to only RTK float (or is that the same thing as DGPS?)
Cheers, Paul

**Comment by geofrancis** [comment]
i think value 4 depends on if your using RTK or not, if using RTK i think 4 = float but with no RTK its DGPS, let me double check.

**Comment by geofrancis** [comment]
yes i made a mistake its recently been changed
https://github.com/ArduPilot/ardupilot/issues/5437
```

  <enum name="GPS_FIX_TYPE">
              <description>Type of GPS fix</description>
              <entry value="0" name="GPS_FIX_TYPE_NO_GPS">
                  <description>No GPS connected</description>
              </entry>
              <entry value="1" name="GPS_FIX_TYPE_NO_FIX">
                  <description>No position information, GPS is connected</description>
              </entry>
              <entry value="2" name="GPS_FIX_TYPE_2D_FIX">
                  <description>2D position</description>
              </entry>
              <entry value="3" name="GPS_FIX_TYPE_3D_FIX">
                  <description>3D position</description>
              </entry>
              <entry value="4" name="GPS_FIX_TYPE_DGPS">
                  <description>DGPS/SBAS aided 3D position</description>
              </entry>
              <entry value="5" name="GPS_FIX_TYPE_RTK_FLOAT">
                  <description>RTK float, 3D position</description>
              </entry>
              <entry value="6" name="GPS_FIX_TYPE_RTK_FIXED">
                  <description>RTK Fixed, 3D position</description>
              </entry>
              <entry value="7" name="GPS_FIX_TYPE_STATIC">
                  <description>Static fixed, typically used for base stations</description>
              </entry>
        </enum>
```

**Comment by geofrancis** [comment]
let me do a pull request for my edits,

**Comment by geofrancis** [comment]
what do you use to edit the lua script?

**Comment by geofrancis** [comment]
nevermind im being an idiot trying to open compilled files

**Comment by athertop** [comment]
I'll sort it bud, don't need to edit/submit pull etc. You certain on the 2 letter labels you suggested?

**Comment by athertop** [comment]
I'll sort it bud, don't need to edit/submit pull etc. You certain on the 2 letter labels you suggested?

**Comment by geofrancis** [comment]
```
if telem_lock >=7 then
      lcd.drawText (168, 10, "ST",0)
      lcd.drawNumber (195, 10, telem_sats, 0+LEFT)
      lcd.drawText (lcd.getLastPos(), 10, "S", 0)
  elseif telem_lock=6 then
      lcd.drawText (168, 10, "FX", 0)
      lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
      lcd.drawText (lcd.getLastPos(), 10, "S", 0)
  elseif telem_lock=5 then
       lcd.drawText (168, 10, "FL", 0)
       lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
       lcd.drawText (lcd.getLastPos(), 10, "S", 0)
  elseif telem_lock=4 then
      lcd.drawText (168, 10, "DG", 0)
      lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
      lcd.drawText (lcd.getLastPos(), 10, "S", 0)
  elseif telem_lock=3 then
      lcd.drawText (168, 10, "3D", 0)
      lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
      lcd.drawText (lcd.getLastPos(), 10, "S", 0)
  elseif telem_lock=2 then
      lcd.drawText (168, 10, "2D", 0)
      lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
      lcd.drawText (lcd.getLastPos(), 10, "S", 0)
  else
      lcd.drawText (168, 10, "NO", 0+BLINK+INVERS)
      lcd.drawText (195, 10, "--S",0)

    end
```

**Comment by geofrancis** [comment]
keep in mind i cant code and just copy and pasted so i have no idea if that will work.

**Comment by athertop** [comment]
How does this look instead - less code, and hopefully more efficient:
```
if telem_lock <= 1 then
  lcd.drawText (168, 10, "NO", 0+BLINK+INVERS)
  lcd.drawText (195, 10, "--S",0)
else
  if telem_lock == 2 then lcd.drawText (168, 10, "2D", 0)
  elseif telem_lock == 3 then lcd.drawText (168, 10, "3D", 0)
  elseif telem_lock == 4 then lcd.drawText (168, 10, "DG", 0)
  elseif telem_lock == 5 then lcd.drawText (168, 10, "FL", 0)
  elseif telem_lock == 6 then lcd.drawText (168, 10, "FX", 0)
  elseif telem_lock >= 7 then lcd.drawText (168, 10, "ST",0)
  end
  lcd.drawNumber (195, 10, telem_sats, 0+LEFT )
  lcd.drawText (lcd.getLastPos(), 10, "S", 0)
end
```

**Comment by athertop** [comment]
I just did a commit to dev branch, but forgot to do the luac compile of this. Will have to wait until tomorrow as getting late and needs me to boot to Windows to run old version of Companion to do the compile.

**Comment by geofrancis** [comment]
looks good, il try and test it some time this week.

**Comment by geofrancis** [comment]
i have been playing with custom sensors on the taranis just to see if i could do anything useful and i remembered about feature in minimosd that gave you glide distance if your throttle was at zero 

so it got me thinking about what other virtual sensors that could be made 

glide ratio, Vspeed/airspeed

**Comment by athertop** [comment]
George, Just added the compiled version here: https://github.com/athertop/MavLink_FrSkySPort/blob/Mav_Sport2.1-2.2-dev/Taranis/LUA_SD_Card/SCRIPTS/TELEMETRY/LIBRARY/mainrun.lib

so replacing the version on your SD card with this one will allow you to test it - I haven't so please let me know how you get on.

In answer to an earlier question, I edit the files on my Mac using a combo of Github desktop (which gives me a locally synced copy of the files), and an editor called Atom - which is really good as an editor for loads of different languages. I have also used a LUA editor in the past called ZeroBraneStudio (its free and a general LUA editor, available for Windows too). You can use it to run the LUA too as it has its own interpreter/runtime - but not that much use for OpenTx directly - great to learn LUA though in the general sense. You have to bear in mind though that LUA in OpenTx is a cut-down version, so not all of the LUA libraries are available in OpenTx version. OpenTx has limited memory also, so it can be a challenge to get something running without running out of memory. OpenTx LUA manual is here: https://www.gitbook.com/book/opentx/opentx-2-2-lua-reference-guide/details

I compile the luac files (which I rename afterwards to .lib) inside companion simulator - I have a Companion v2 release which was built by Luis Vale which runs in windows only - it has the LUA compiler option enabled when it was compiled, so when you try to run a telem1.lua file (for example) it creates a telem1.luac file in the same <model_name> folder (remember Opentx v2.0 and the model folder for scripts?) Well, that's how I create the compiled files anyway.

Cheers, Paul

**Comment by geofrancis** [comment]
this works fine shows gps status great.
