### ISSUE TITLE
Taranis X7 screen layout

### ISSUE THREAD

**Issue by ausi1972** [athertop/MavLink_FrSkySPort#21]
Any chance of getting a version to fit in the new FrSky Taranis Q X7

**Comment by athertop** [comment]
Sorry, I don't have an x7 to try this. Also no ability to compile the code (only have an old version of companion which has the compile option - bit of a hack needed to run the code inside the tight memory availability of the Taranis). Its open source though so you can feel free to create a fork and develop it yourself. Cheers
