### ISSUE TITLE
Arduino Pro Mini compatibility

### ISSUE THREAD

**Issue by kormitigrov** [athertop/MavLink_FrSkySPort#24]
Hi, guys! I've seen several outdated branches of your wonderful project with arduino pro mini support. I couldn't find any of it in this *official* version. Do you allow users to switch between Teensy and Arduino, or you have never adapted this code to the latter?

**Comment by athertop** [comment]
The code was advanced a while ago which meant it being only compatible on Teensy 3.1/3.2/LC. Sorry, no other Arduino boards.
