### ISSUE TITLE
Batt2 Sensor

### ISSUE THREAD

**Issue by Juzzle1** [athertop/MavLink_FrSkySPort#4]
Would it be possible get sensor data from the second battery (BATT2)? On recent versions of Copter / Plane this is sent over Mavlink just like Battery 1.

I only need the additional sensor data to be sent to the Taranis (no need for it on LUA screen), but Pixhawk 2 users will likely need this too as it has two current/voltage sensor inputs for dual battery setups.

**Comment by athertop** [comment]
I'll take a look at this. Should be possible,  but will require you to turn on this functionality as an option in the addons/options section of the teensy code once I have added the new code. May take a few weeks as I'm on vacation just now.

**Comment by athertop** [comment]
@Juzzle1 - Can I please verify that in addition to using two battery sensors, you do not also have installed OpenTx FLVSS (or any other battery) sensors? The reason I ask, is that I plan to use the telemetry sensor ID 15 for the BATT2 device (which is also used by a second FLVSS sensor should one be installed). So using BATT2 you would not be able to also have  FLVSS FrsSky sensors configured. Thanks

**Comment by Juzzle1** [comment]
Thanks for looking into this. 

No other sensors in use here, just Pixhawk -> Teensy -> S.Port

**Comment by athertop** [comment]
@Juzzle1 - I have just uploaded changed Teensy code to https://github.com/athertop/MavLink_FrSkySPort/tree/Mav_Sport2.1-2.2-dev/Teensy/MavLink_FrSkySPort (this is the -dev branch) which includes a BATT2 feature.
This must be enabled under features section in MavLink_FrSkySPort.ino. Once you run sensor discovery you should see 2 new (additional/duplicate) VFAS and Curr sensors, both will appear with sensor instance 15 (check the sensor IDs to locate these two new sensors one). These must be renamed by editing these 2 new sensors (with ID 15) to keep the names different from the two original VFAS and Curr sensors). So maybe rename the new ones to say FAS2 and CUR2 if you like.
This has been tested for compilation but I am not able to test the functionality in practise as I don't have a Pixhawk 2.1 with 2 power bricks. Also note that although the teensy code is updated here to create the new sensor, this does not yet appear on the LUA Telemetry screen. I will sort this later for you if you need it. If you can please test this.
Some notes on limitations in its use: 
* if the USE_BATT2 feature is enabled then you can not have either of the features USE_SINGLE_CELL_MONITOR or USE_FLVSS_FAKE_SENSOR_DATA also enabled if MAXCELLS is set to >6 - as this would create another (FLVSS sensor called Cels) sensor also using ID15 so a clash.
* The original VFAS and Curr sensors are put through an averaging process in the code. I was unable to do this for the BATT2 provided sensors as it would require significant work in the average.ino code, so I don't know how this will affect the display of the new sensors. I image these should be fine though.
Please let me know if it all works. Thanks, Paul

**Comment by Juzzle1** [comment]
Hi Paul,

This sounds great. 

FYI, I'm actually using this with a Pixhawk 1, with BAT2 currently configured to use the 6.6V ADC which is reading the voltage from a Mauch Sensor Hub relay output. 
I have 2 batteries connected and the sensor hub outputs 5V when both batteries are discharging with a similar current, and 0V when there is >20% difference in discharge rate (e.g. when one battery is not connected or is at a different charge level).

So as long as I can get BAT2 values down to the Taranis (right now I can only see the value in mission planner), I can set up an audible alert when BAT2 = 0V (fault condition).

I'm using my aircraft tomorrow morning, so I'm not going to fiddle with / break anything tonight, but will have a go tomorrow evening if I have time.

Thanks so much for doing this!

Justin

**Comment by athertop** [comment]
Just checked out the sensor hub - first time I've seen this configuration. Looks awfully complex for what essentially is 2 Lipos in parallel, but I see it's benefits for redundancy, so a nice solution. I also run two Lipos in parallel but my lipo monitoring follows a different path. For me, both 4s Lipos are wired to the input of one 180a attopilot voltage/current sensor. This is similar to the 3dr battery brick but provides no voltage regulator, so I also utilise a linear BEC to power the Pixhawk. Both this power and the voltage/current inputs connect into the power connector of the pixhawk. Additionally I make use of  two FrSky FLVSS lipo sensors, each used to monitor the 4 cells of its connected lipo via the LiPo balance connector. I have these FrSky sensors configured, one with the default instance ID  of 2, and the other modified to ID 15 to keep these unique,  and both show up on the Taranis telemetry sensors page where I have additional calculated sensors configured to give me the minimum voltage cell value of each LiPo, then one further Cmin sensor giving the minimum of these two. The sensor configured with the name Cmin is that which will be displayed on the main telemetry screen. The attopilot provides v/a to the Pixhawk which appears as VFAS/Curr in the Frsky telemetry sensors page. These values are displayed also on the main telemetry screen, and also used as sources for the calculated Watt sensor,which is also displayed on the main telemetry screen. The Watt sensor is used by the LUA code to determine the Wh value also displayed and used as battery capacity.

**Comment by Juzzle1** [comment]
Sorry I've not had a chance to test this yet. Hopefully I'll have some time tonight or tomorrow. I'll keep you posted.

I went for the Mauch sensors as they use much more accurate hall effect sensors and the manufacturer calibrates them before shipping so you can just plug the provided voltage / current divider values into MP and get accurate readings without fuss. 

Cheers

**Comment by Juzzle1** [comment]
Just tried 2.2-dev with USE_BATT2 enabled, ran sensor discovery and hey presto, I can see the BAT2 voltage reading. 

From what I can see, everything else seems to be working normally as before.

I'll take it out for a proper spin at the weekend (weather permitting), but testing on the bench looks good.

Thanks for putting the time in on this, much appreciated.

Justin

**Comment by athertop** [comment]
BATT2 was moved to the current master a while ago. Closing
